### ISSUE TITLE
[Bug] Recaptcha

### ISSUE THREAD

**Issue by McFanta** [OverrideNetwork/Website#16]
So hello guys, I recently found a major known bug here with the recaptcha thing. It should work but any of you guys must have done something wrong with the code which you actually easily can fix if you code it right. The message I get in norwegian is <b>FEIL til eieren av nettstedet: Invalid site key</b> and in english it means <b>FAILURE to the site owner: Invalid site key</b>. 

And this should not happen generally also my account got removed because of the major forum update too so I tried to sign up but It didn't work. Right now I can't think of a code that will solve this problem.

Screenshot of the bug down below:

![screenshot_453](https://cloud.githubusercontent.com/assets/13437351/15631968/1844b378-2583-11e6-912b-f88ad7137559.png)

Also if you need any extra developers, I could fit in there. Let me know that when the sign in thing is fixed and please let me know if you want help. Contact me on team speak or skype. Just ask me for it.

**Comment by Prodigy4532** [comment]
Thanks for the issue

**Comment by vYuri** [comment]
Fixed, thanks for the report.
